name: Deploy to AWS s3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: NodeJs Setup
        uses: actions/setup-node@v3
        with:
          node-version: ${{secrets.NODE_VERSION}}

      - name: Install dependencies
        run: |
          cd portfolio-app
          npm install

      - name: Build React App
        run: |
          cd portfolio-app
          npm install

      - name: Configure AWS Credentials
        uses: aws-action/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: us-west-2

      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --acl public-read --delete ./portfolio-app/build/ s3://${{ secrets.AWS_S3_BUCKET_NAME }}
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-west-2
